ALTER TABLE "Word" ADD COLUMN "pronunciation" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Word" ADD COLUMN "wordForms" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Word" ADD COLUMN "synonyms" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Word" ADD COLUMN "antonyms" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Word" ADD COLUMN "collocations" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Word" ADD COLUMN "toeicContext" TEXT NOT NULL DEFAULT '';
