export const wordSuggestionSchema: Record<string, unknown> = {
  type: 'object',
  additionalProperties: false,
  properties: {
    meaning: { type: 'string', maxLength: 200 },
    example: { type: 'string', maxLength: 500 },
    cefrLevel: { type: 'string', enum: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', ''] },
    partOfSpeech: { type: 'string', maxLength: 50 },
    register: { type: 'string', maxLength: 30 },
    frequency: { type: 'string', maxLength: 30 },
    pronunciation: { type: 'string', maxLength: 80 },
    pronunciationUS: { type: 'string', maxLength: 80 },
    pronunciationUK: { type: 'string', maxLength: 80 },
    syllables: { type: 'string', maxLength: 50 },
    stressPattern: { type: 'string', maxLength: 80 },
    senses: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          definition: { type: 'string', maxLength: 300 },
          translation: { type: 'string', maxLength: 300 },
          examples: { type: 'array', items: { type: 'string', maxLength: 500 }, maxItems: 5 },
          usageNotes: { type: 'string', maxLength: 300 },
        },
        required: ['definition', 'translation', 'examples', 'usageNotes'],
      },
      maxItems: 20,
    },
    wordForms: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          partOfSpeech: { type: 'string', maxLength: 30 },
          form: { type: 'string', maxLength: 100 },
          meaning: { type: 'string', maxLength: 200 },
        },
        required: ['partOfSpeech', 'form', 'meaning'],
      },
    },
    synonyms: { type: 'array', items: { type: 'string', maxLength: 100 } },
    antonyms: { type: 'array', items: { type: 'string', maxLength: 100 } },
    collocations: { type: 'array', items: { type: 'string', maxLength: 200 } },
    grammarPatterns: { type: 'array', items: { type: 'string', maxLength: 200 }, maxItems: 20 },
    context: { type: 'string', maxLength: 200 },
  },
  required: [
    'meaning',
    'example',
    'cefrLevel',
    'partOfSpeech',
    'register',
    'frequency',
    'pronunciation',
    'pronunciationUS',
    'pronunciationUK',
    'syllables',
    'stressPattern',
    'senses',
    'wordForms',
    'synonyms',
    'antonyms',
    'collocations',
    'grammarPatterns',
    'context',
  ],
};
